### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by cellear** [backdrop-ops/crm.backdropcms.org#1]
Well will you look at this...it looks like we have a CRM!

Yipee!

:)

**Comment by stpaultim** [comment]
We need need someplace to put it. 

I am assuming that this repo is vanilla Backdrop and vanilla CiviCRM at this point. I may try to spin it up on the Triplo dev linode.

**Comment by jenlampton** [comment]
Civi is being installed onto the main backdropcms.org site, so I'm going to close this issue, and delete the repo.
